### ISSUE TITLE
Bootstrap 3 input:focus black outline-color fix

### ISSUE THREAD

**Issue by isglazunov** [mdbootstrap/bootstrap-templates#31]
``` css
.bootstrap-tagsinput input {
    outline-color: transparent;
}
```

Add this to the styles that-be in version 2 Bootstrap was not at a border input.
